# Generated by Django 3.0.4 on 2020-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('tags', models.CharField(max_length=10)),
                ('liked_or_not', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
