# Generated by Django 3.0.7 on 2020-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200611_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
