# Generated by Django 3.0.7 on 2020-06-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200616_1613'),
    ]

    operations = [
        migrations.RenameModel('Likes', 'Like'),
        migrations.RenameModel('Follows', 'Follow'),
    ]
